// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
let verifier = artifacts.require("SquareVerifier");

// Test verification with correct proof
let proof = require("../../zokrates/code/square/proof");

contract("TestSquareVerifier", (accounts) => {
  const test_acc = accounts[0];
});
